spring.application.name=back

# Base de datos - MISMA CONFIGURACIÓN para local y Render
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backmastercuts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.jdbc=DEBUG


#Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dwjgugsb4}
cloudinary.api_key=${CLOUDINARY_API_KEY:445713156149539}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:6MKTOal8QYxPkH2WRx4sPZekQnE}